version: "3.9"
services:
  db-service:
    container_name: "db-service"
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=student-db
      - MYSQL_USER=new-user
      - MYSQL_PASSWORD=appleW00d
    volumes:
      - "db_data:/var/lib/mysql"
   

  student-service:
    container_name: "student-service"
    image: "student-service-img"
    build:
      context: .
    restart: always
    environment:
      - DB_USER=new-user
      - DB_PASSWORD=appleW00d
      - DB_SERVICE=db-service
      - DB_NAME=student-db        

    depends_on:
      - db-service
    ports:
      - "80:5000"
   
volumes:
    db_data:

